"use strict";

export const ETX_CHARACTER = "\u0003";
export const COLON_CHARACTER = ":";
export const PERIOD_CHARACTER = ".";
export const CTRL_C_CHARACTER = "^C";
export const WILDCARD_CHARACTER = "*";
export const NEW_LINE_CHARACTER = "\n";
export const AMPERSAND_CHARACTER = "&";
export const LINE_FEED_CHARACTER = "\n";
export const BACKSPACE_CHARACTER = String.fromCharCode(127);
export const LESS_THAN_CHARACTER = "&lt;";
export const GREATER_THAN_CHARACTER = "&gt;";
export const FORWARD_SLASH_CHARACTER = "/";
export const CARRIAGE_RETURN_CHARACTER = "\r";
export const EXCLAMATION_MARK_CHARACTER = "!";

export default {
  ETX_CHARACTER,
  COLON_CHARACTER,
  PERIOD_CHARACTER,
  CTRL_C_CHARACTER,
  WILDCARD_CHARACTER,
  NEW_LINE_CHARACTER,
  AMPERSAND_CHARACTER,
  LINE_FEED_CHARACTER,
  BACKSPACE_CHARACTER,
  LESS_THAN_CHARACTER,
  GREATER_THAN_CHARACTER,
  FORWARD_SLASH_CHARACTER,
  CARRIAGE_RETURN_CHARACTER,
  EXCLAMATION_MARK_CHARACTER
};
