"use strict";

export const ETX_CHARACTER = "\u0003";
export const COLON_CHARACTER = ":";
export const CTRL_C_CHARACTER = "^C";
export const WILDCARD_CHARACTER = "*";
export const AMPERSAND_CHARACTER = "&";
export const LINE_FEED_CHARACTER = "\n";
export const BACKSPACE_CHARACTER = String.fromCharCode(127);
export const FORWARD_SLASH_CHARACTER = "/";
export const CARRIAGE_RETURN_CHARACTER = "\r";
export const EXCLAMATION_MARK_CHARACTER = "!";

export default {
  ETX_CHARACTER,
  COLON_CHARACTER,
  CTRL_C_CHARACTER,
  WILDCARD_CHARACTER,
  AMPERSAND_CHARACTER,
  LINE_FEED_CHARACTER,
  BACKSPACE_CHARACTER,
  FORWARD_SLASH_CHARACTER,
  CARRIAGE_RETURN_CHARACTER,
  EXCLAMATION_MARK_CHARACTER
};
