"use strict";

export const OK_200_STATUS_CODE = 200;
export const FOUND_302_STATUS_CODE = 302;
export const INTERNAL_SERVER_ERROR_STATUS_CODE = 501;

export default {
  OK_200_STATUS_CODE,
  FOUND_302_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE
};
